
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Sample Data for Report Card
song_data = {
    "Track Name": "Midnight Rush",
    "Artist": "Nova Bleu",
    "Hit Score": 76,
    "Tempo": 85,
    "Avg Tempo": 104,
    "Energy": 0.55,
    "Avg Energy": 0.78,
    "Danceability": 0.73,
    "Avg Danceability": 0.72,
    "Valence": 0.31,
    "Avg Valence": 0.65,
    "Lyrical Density": 5.2,
    "Avg Lyrical Density": 4.7
}

st.set_page_config(page_title="HitSense Report Card", layout="centered")
st.title("🎓 HitSense: Song Report Card")

# Summary
st.header("🔍 Song Summary")
col1, col2 = st.columns(2)
col1.metric("Track Name", song_data["Track Name"])
col1.metric("Artist", song_data["Artist"])
col2.metric("Hit Score", f"{song_data['Hit Score']}%", delta=None)

# Feature Comparison Table
st.header("📊 Feature Breakdown")
features = ["Tempo", "Energy", "Danceability", "Valence", "Lyrical Density"]
comparison = {
    "Feature": [],
    "Your Song": [],
    "Top 100 Avg": [],
    "Status": []
}
for f in features:
    user_val = song_data[f]
    avg_val = song_data[f"Avg {f}"]
    status = "✅ Good" if abs(user_val - avg_val) < 0.1 else ("⚠️ Needs Adjusting" if abs(user_val - avg_val) < 0.2 else "⛔ Off")
    comparison["Feature"].append(f)
    comparison["Your Song"].append(user_val)
    comparison["Top 100 Avg"].append(avg_val)
    comparison["Status"].append(status)

comp_df = pd.DataFrame(comparison)
st.dataframe(comp_df)

# Insights
st.header("🧠 AI Insights")
st.markdown("""
- **Observations**:
    - Strong danceability and lyrical structure.
    - Energy and valence are lower than hit average.
- **Suggestions**:
    - Increase tempo or percussion to raise energy.
    - Consider adding a harmonic lift or key change in the chorus.
""")

# Chart
st.header("📈 Hit Probability Meter")
fig, ax = plt.subplots()
ax.barh(["Hit Potential"], [song_data["Hit Score"]], color='green')
ax.set_xlim(0, 100)
ax.set_xlabel("% Likelihood")
st.pyplot(fig)

# Footer
st.caption("Generated by HitSense AI — Demo Report")
